packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@embedded-postgres/windows-x64"
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
